console.log("event file called !...");
module.exports = {
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    VERIFY_USER: 'VERIFY_USER',
    LOGOUT: 'LOGOUT',
    USER_LIST: 'USER_LIST',
    PRIVATE_ROOM: 'PRIVATE_ROOM',
    PLAYING: 'PLAYING',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION',
    RECEIVED_NOTIFICATION: 'RECEIVED_NOTIFICATION',
    USER_SIGNOUT: 'USER_SIGNOUT',
    SET_MOVE: 'SET_MOVE'
}